---
title: "Block Permutation NFL Elo"
author: "Maximilian J. Gebauer"
date: "2026-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(data.table)
library(furrr)

# ---------------------------
# Read and build analysis data
# ---------------------------
hudl <- read.csv("~/Downloads/Analytics Summer Lab/hudl_iq_game_ids.csv") %>%
  mutate(
    week = stringr::str_extract(nflfast_game_id, "(?<=^\\d{4}_)\\d{2}")
  )

results2 <- read.csv("~/Downloads/results2.csv") %>%
  left_join(hudl %>% select(game_id, week), by = "game_id")

sacks <- read.csv("~/Downloads/sacks.csv")

hits  <- read.csv("~/Downloads/hits.csv")

results2 <- results2 %>%
  left_join(
    sacks %>% select(game_id, play_uuid, sack_player, sack),
    by = c("game_id", "play_id" = "play_uuid", "rusher_name" = "sack_player")
  ) %>%
  mutate(sack = replace_na(sack, 0L)) %>%
  left_join(
    hits %>% select(game_id, play_uuid, hit_player, hit),
    by = c("game_id", "play_id" = "play_uuid", "rusher_name" = "hit_player")
  ) %>%
  mutate(hit = replace_na(hit, 0L)) %>%
  mutate(
    outcome_score = case_when(
      sack == 1L       ~ 1.0,
      hit == 1L        ~ 0.4,
      rusher_won == 1L ~ 0.2,
      TRUE             ~ 0.0
    )
  )

results_cleaned <- results2 %>%
  drop_na(game_id, rusher_name, blocker_name) %>%
  mutate(week = replace_na(week, "UNK")) %>%
  arrange(game_id, play_id, event_game_index) %>%
  select(
    game_id, play_id, event_game_index, week,
    rusher_name, blocker_name, double_team, outcome_score
  )

# ---------------------------
# Initial ratings
# ---------------------------
init_play_ratings <- results_cleaned %>%
  select(rusher_name, blocker_name) %>%
  pivot_longer(everything(), names_to = "type", values_to = "player_name") %>%
  mutate(Player_Elo = ifelse(type == "rusher_name", 750, 1125)) %>%
  distinct(player_name, .keep_all = TRUE)

initial_elo_vec <- setNames(init_play_ratings$Player_Elo, init_play_ratings$player_name)
all_weeks <- sort(unique(results_cleaned$week))
```

```{r}
adaptive_K_prov <- function(n, K_start, K_min, n_prov, n_decay) {
  k <- ifelse(
    n <= n_prov,
    K_start,
    ifelse(
      n <= n_decay,
      K_start + (K_min - K_start) * (n - n_prov) / (n_decay - n_prov),
      K_min
    )
  )
  pmax(k, K_min)
}

elo_step <- function(
  belo, relo, outcome_score, blocker_K, rusher_K,
  double_team, scale = 319
) {
  if (is.na(outcome_score)) return(c(b = belo, r = relo))

  blocker_bonus <- ifelse(double_team == 1, 100, 0)
  adj_belo <- belo + blocker_bonus

  exp_rusher <- 1 / (1 + 10 ^ ((adj_belo - relo) / scale))

  c(
    b = belo + blocker_K * ((1 - outcome_score) - (1 - exp_rusher)),
    r = relo + rusher_K  * ( outcome_score      -      exp_rusher)
  )
}
```

```{r}
run_week_order_elo <- function(data, week_order, initial_elo_vec, iter_id = NA_integer_) {
  # Map each week to its new position
  week_lookup <- tibble(
    week = week_order,
    week_perm_order = seq_along(week_order)
  )

  dat <- data %>%
    left_join(week_lookup, by = "week") %>%
    arrange(week_perm_order, game_id, play_id, event_game_index) %>%
    group_by(rusher_name) %>%
    mutate(rusher_row = row_number()) %>%
    ungroup() %>%
    group_by(blocker_name) %>%
    mutate(blocker_row = row_number()) %>%
    ungroup() %>%
    mutate(
      rusher_k = adaptive_K_prov(
        n = rusher_row, K_start = 20, K_min = 10, n_prov = 87, n_decay = 200
      ),
      blocker_k = adaptive_K_prov(
        n = blocker_row, K_start = 20, K_min = 10, n_prov = 87, n_decay = 200
      )
    )

  dat <- as.data.table(dat)

  elo_vec <- initial_elo_vec

  get_elo_local <- function(id) {
    id <- as.character(id)
    if (!id %in% names(elo_vec)) elo_vec[[id]] <<- 1000
    elo_vec[[id]]
  }

  for (i in seq_len(nrow(dat))) {
    r_id <- dat$rusher_name[i]
    b_id <- dat$blocker_name[i]
    out  <- dat$outcome_score[i]
    r_K  <- dat$rusher_k[i]
    b_K  <- dat$blocker_k[i]
    d_t  <- dat$double_team[i]

    if (is.na(r_id) || is.na(b_id) || is.na(out)) next

    r_elo <- get_elo_local(r_id)
    b_elo <- get_elo_local(b_id)

    new <- elo_step(
      belo = b_elo,
      relo = r_elo,
      outcome_score = out,
      blocker_K = b_K,
      rusher_K = r_K,
      double_team = d_t
    )

    if (!any(is.na(new))) {
      elo_vec[[r_id]] <- new["r"]
      elo_vec[[b_id]] <- new["b"]
    }
  }

  tibble(
    iter = iter_id,
    player_name = names(elo_vec),
    final_elo = unname(elo_vec)
  )
}
```

```{r}
player_roles <- results_cleaned %>%
  select(rusher_name, blocker_name) %>%
  pivot_longer(cols = everything(), values_to = "player_name") %>%
  mutate(role = ifelse(name == "rusher_name", "Rusher", "Blocker")) %>%
  distinct(player_name, role)
```

```{r}
set.seed(5710)

B <- 1000


week_orders <- replicate(
  B,
  sample(all_weeks, length(all_weeks), replace = FALSE),
  simplify = FALSE
)

start_time <- Sys.time()

plan(multisession, workers = parallelly::availableCores() - 1)

elo_bootstrap_results <- future_map2_dfr(
  .x = week_orders,
  .y = seq_along(week_orders),
  .f = ~ run_week_order_elo(
    data = results_cleaned,
    week_order = .x,
    initial_elo_vec = initial_elo_vec,
    iter_id = .y
  ),
  .options = furrr_options(seed = TRUE)
) %>%
  left_join(player_roles, by = "player_name")
end_time <- Sys.time()
print(end_time - start_time)
```

```{r}
elo_summary <- elo_bootstrap_results %>%
  group_by(player_name, role) %>%
  summarise(
    mean_final_elo = mean(final_elo, na.rm = TRUE),
    sd_final_elo   = sd(final_elo, na.rm = TRUE),
    q025           = quantile(final_elo, 0.025, na.rm = TRUE),
    q50            = quantile(final_elo, 0.50,  na.rm = TRUE),
    q975           = quantile(final_elo, 0.975, na.rm = TRUE),
    .groups = "drop"
  )
```

```{r}
elo_summary %>%
  filter(role=="Blocker") %>% 
  arrange(desc(mean_final_elo)) %>%
  head(20)
elo_summary %>%
  filter(role=="Rusher") %>% 
  arrange(desc(mean_final_elo)) %>%
  head(20)
```













